#define IDR_MAINFRAME                   128
#define ID_AFTERSTART                   129
#define IDR_MAIN                        130
#define ID_TAB                          130
#define IDD_PROGRESS                    131
#define IDD_BATCH                       132
#define IDD_BARVIEW                     133
#define IDD_WVSS_MAIN                   136
#define IDD_PAGE_AIRCRAFT               138
#define IDD_PAGE_SEVERITY_RESULTS       139
#define IDD_PAGE_OVERRIDE               140
#define IDD_PAGE_DISPLAY                141
#define IDD_PAGE_INTERACTION            142
#define IDD_PAGE_WAKE_OPTIONS           142
#define IDD_PAGE_LOAD                   143
#define IDD_PAGE_INFO                   144
#define IDD_PAGE_FRAME                  145
#define IDD_PAGE_COMMS                  146
#define IDD_PAGE_AIRCRAFT1              147
#define IDD_PAGE_SENSITIVITY            147
#define IDD_PAGE_WEATHER                148
#define IDD_PAGE_WAKE_INTERACTION       149
#define IDB_LOAD                        1000
#define IDS_FILE                        1001
#define IDL_STATUS                      1002
#define IDB_RELOAD                      1003
#define IDB_PLAY                        1004
#define IDC_SCROLL1                     1006
#define IDO_TS                          1008
#define IDE_CURPOS                      1009
#define IDS_CURPOS                      1010
#define IDB_CURPOS                      1011
#define IDE_WINDDIRECTION               1012
#define IDE_WINDSPEED                   1013
#define IDE_MIN_GAMMA                   1014
#define IDO_PLAYSPEED                   1015
#define IDE_dZ                          1020
#define IDE_dH                          1021
#define IDB_CUR_FRAME                   1022
#define IDE_dAngle                      1023
#define IDB_CLEAR_HISTORY               1024
#define IDE_PLANE_SIZE                  1025
#define IDB_SAVE_HISTORY                1026
#define IDE_WAKE_SIZE                   1027
#define IDE_OVERRIDE_GAMMA              1028
#define IDC_DZDHOVERRIDE                1035
#define IDC_EMULATE_FLIGHT              1036
#define IDE_INITIALPLANETOWAKECROSSDISTANCE 1037
#define IDC_CALC_SEVERITY               1038
#define IDO_PILOT_RESPONSE              1039
#define IDO_SCENARIO                    1040
#define IDS_TEXT1                       1041
#define IDC_PROGRESS                    1042
#define IDC_USE_GROUND_EFFECT_ALGORITHM 1044
#define IDS_TIME                        1045
#define IDC_USE_STRATIFICATION_EFFECT_ALGORITHM 1045
#define IDB_HELP                        1046
#define IDC_USE_STRATIFICATION_EFFECT_ALGORITHM2 1046
#define IDC_USE_COU_FOR_SEVERITY        1046
#define IDO_FILE_TYPE                   1047
#define IDO_FLIGHT_SPEED                1048
#define IDSC_dZ                         1049
#define IDE_FLIGHT_TIME                 1050
#define IDC_FLIGHT_AUTO_STOP            1051
#define IDS_FLIGHT_TIME                 1052
#define IDSC_dH                         1053
#define IDS_FLIGHT_TIME2                1053
#define IDE_START_DZ                    1054
#define IDE_END_DZ                      1055
#define IDR_BY_OVERRIDE                 1057
#define IDE_START_DH                    1058
#define IDB_BATCH                       1058
#define IDE_END_DH                      1059
#define IDP_PROGRESS                    1059
#define IDR_BY_FRAME                    1060
#define IDC_MAKE_AUX_FILES              1060
#define IDE_SHOW_SECTIONS               1061
#define IDE_START_FRAME                 1062
#define IDE_END_FRAME                   1063
#define IDB_BARVIEW                     1063
#define IDB_MAIN_VIEW                   1064
#define IDB_COMMS_CONNECT               1064
#define IDC_AIR_BLOCKS                  1065
#define IDC_SHOW_CONE_OF_UNCERTAINTY    1066
#define IDC_OVERRIDE_GAMMA              1067
#define IDC_DEBUG_MESSAGES              1067
#define IDS_dZ                          1068
#define IDC_SHOW_LINES_FROM_AC_CENTER   1068
#define IDS_dH                          1069
#define IDC_SHOW_LINES_FROM_AC_CENTER2  1069
#define IDC_SHOW_LINES_FROM_WINGTIPS    1069
#define IDS_dAngle                      1070
#define IDC_REAL_WEATHER                1071
#define IDC_SEVERITY_RES_LIST           1072
#define IDC_NO_WIND_EXTRAPOLATION       1072
#define IDC_AIRCRAFT_LIST               1073
#define IDB_SETFRAME                    1077
#define IDC_FRAME_LIST_PLANE            1078
#define IDC_FRAME_LIST_WAKE             1079
#define IDL_INFO                        1079
#define IDC_SENSITIVITY_LIST            1080
#define IDC_WEATHER_LIST                1081
#define IDE_WAKESECTIONTOWINGTIPTOLERANCE 1082
#define IDO_RING_AIRCRAFT               1083
#define IDO_VIS_CENTER_ON               1084
#define IDB_VIS_CENTER_ON               1085
#define IDC_VIS_CENTER_ON               1086
#define IDC_WAKEFRAME_LIST_INTERACTION  1087
#define IDE_OVERRIDE_BATCH_RESULTS      1089
#define IDE_CIRCLE_RADII                1090
#define IDS_BUILD_INFO                  1091
#define ID_MOVE_UL                      32771
#define ID_MOVE_UR                      32772
#define ID_MOVE_LL                      32773
#define ID_MOVE_LR                      32774
#define ID_TIME_NEXT                    32776
#define ID_TIME_PREV                    32777
#define IDS_WSAEINTR                    50004
#define IDS_WSAEACCES                   50013
#define IDS_WSAEFAULT                   50014
#define IDS_WSAEINVAL                   50022
#define IDS_WSAEMFILE                   50024
#define IDS_WSAEWOULDBLOCK              50035
#define IDS_WSAEINPROGRESS              50036
#define IDS_WSAEALREADY                 50037
#define IDS_WSAENOTSOCK                 50038
#define IDS_WSAEMSGSIZE                 50040
#define IDS_WSAEPROTOTYPE               50041
#define IDS_WSAEPROTONOSUPPORT          50043
#define IDS_WSAEOPNOTSUPP               50045
#define IDS_WSAEAFNOSUPPORT             50047
#define IDS_WSAEADDRINUSE               50048
#define IDS_WSAEADDRNOTAVAIL            50049
#define IDS_WSAENETDOWN                 50050
#define IDS_WSAENETUNREACH              50051
#define IDS_WSAENETRESET                50052
#define IDS_WSAECONNABORTED             50053
#define IDS_WSAECONNRESET               50054
#define IDS_WSAENOBUFS                  50055
#define IDS_WSAEISCONN                  50056
#define IDS_WSAENOTCONN                 50057
#define IDS_WSAESHUTDOWN                50058
#define IDS_WSAETIMEDOUT                50060
#define IDS_WSAECONNREFUSED             50061
#define IDS_WSAEHOSTUNREACH             50065
#define IDS_WSASYSNOTREADY              50091
#define IDS_WSAVERNOTSUPPORTED          50092
#define IDS_WSANOTINITIALISED           50093
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
